# Generated by Django 5.2.7 on 2025-10-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_client_email_9bd669_idx'), models.Index(fields=['phone'], name='core_client_phone_e857f7_idx'), models.Index(fields=['create_date'], name='core_client_create__ef5dcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_subscr_email_ef2bb6_idx'), models.Index(fields=['create_date'], name='core_subscr_create__01ce5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriberSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='core_subscr_phone_ae0d1c_idx'), models.Index(fields=['create_date'], name='core_subscr_create__62fb6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='core_user_email_38052c_idx'), models.Index(fields=['phone'], name='core_user_phone_18c349_idx'), models.Index(fields=['create_date'], name='core_user_create__c7aa4f_idx')],
            },
        ),
    ]
